# 系统基础配置
system:
  base_url: "https://c1.yonyoucloud.com/"
  download_dir: "D:\\qcyq\\很久以前\\Files"
  video: "D:\\qcyq\\很久以前\\Videos"
  image: "D:\\qcyq\\很久以前\\Images"

# 登录信息
login:
  username: "15210385806"
  password: "lwp12345678"

# 飞书
feishu:
  app_id: "cli_a9a3f1fddbf85cbd"
  app_secret: "y7Oai1UMDi27loppGTC2LgN41rhHGBnP"
  webhook: "https://open.feishu.cn/open-apis/bot/v2/hook/your_webhook"

